apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: targeting-service:v1.0.0
          ports:
            - containerPort: 8080
