apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-auth-service.yaml
  - application-flag-service.yaml
  - application-targeting-service.yaml
  - application-evaluation-service.yaml
  - application-analytics-service.yaml
