apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: evaluation-service:v1.0.0
          ports:
            - containerPort: 8080
